# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from decimal import Decimal

from django.utils.translation import ugettext as _

DEFAULT_USERS_ID = 1

#: File AS status choices
SAV_FILE_STATUS_TYPE_OPENED = 'O'
SAV_FILE_STATUS_TYPE_IN_PROGRESS = 'IP'
SAV_FILE_STATUS_TYPE_PROBLEM = 'P'
SAV_FILE_STATUS_TYPE_CLOSED = 'C'
SAV_FILE_STATUS_CHOICES = (
    (SAV_FILE_STATUS_TYPE_OPENED, _("Opened")),
    (SAV_FILE_STATUS_TYPE_IN_PROGRESS, _("In progress")),
    (SAV_FILE_STATUS_TYPE_PROBLEM, _("Problem")),
    (SAV_FILE_STATUS_TYPE_CLOSED, _("Closed"))
)

#: File AS waranty
SAV_FILE_WARANTY_TYPE_INCLUDED = 'IW'
SAV_FILE_WARANTY_TYPE_EXCLUDED = 'EW'
SAV_FILE_WARANTY_TYPE_CHOICES = (
    (SAV_FILE_WARANTY_TYPE_INCLUDED, _("Included waranty")),
    (SAV_FILE_WARANTY_TYPE_EXCLUDED, _("Excluded waranty")),
)

FONT_STYLE_BOLD = "Helvetica-Bold"
FONT_STYLE = "Helvetica"
FONT_TITLE_SIZE = 20
FONT_NORMAL_SIZE = 12
FONT_SMALLER_SIZE = 10
FONT_SMALL_SIZE = 7
FONT_VERY_SMALL_SIZE = 5
FIELD_SEPARATOR = " : "
NORMAL_SEPARATOR = " - "
COMA_SEPARATOR = ", "

TAX_RATE = Decimal(1.2)

DEFAULT_ASS_FILE_LIST_VIEW_PAGINATION_BY = 40
DEFAULT_WARANTY_LIST_VIEW_PAGINATION_BY = 40
DEFAULT_FURNISHER_LIST_VIEW_PAGINATION_BY = 40

UPDATE_OR_CREATE_TEMPLATE = 'djangoApp/common/createOrUpdate.html'
DELETE_TEMPLATE = 'djangoApp/common/confirmDelete.html'
