# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0004_auto_20171204_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sav_file',
            name='created_by',
        ),
    ]
