# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0006_sav_file_registred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sav_file',
            name='furnisher_invoice',
        ),
    ]
