# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0009_sav_file_reference_sav_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sav_file',
            name='reference_SAV_file',
        ),
    ]
