# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0013_furnisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_file',
            name='furnisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.Furnisher'),
        ),
        migrations.AlterField(
            model_name='furnisher',
            name='commentary',
            field=models.TextField(blank=True),
        ),
    ]
