# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0014_auto_20180425_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnisher',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='furnisher',
            name='zipcode',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='city_client',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='zipcode_client',
            field=models.CharField(default='', max_length=30),
        ),
    ]
