# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0017_auto_20180611_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sav_file',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='sav_file',
            name='rma_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
