# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0019_auto_20180711_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['quantity'], 'verbose_name': 'designation', 'verbose_name_plural': 'designations'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['refered_SAV_file'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='furnisher',
            options={'ordering': ['mark'], 'verbose_name': 'furnisher', 'verbose_name_plural': 'furnishers'},
        ),
        migrations.AlterModelOptions(
            name='guarantee',
            options={'ordering': ['mark'], 'verbose_name': 'waranty', 'verbose_name_plural': 'waranties'},
        ),
        migrations.AlterModelOptions(
            name='sav_file',
            options={'ordering': ['creation_date'], 'verbose_name': 'After sale file', 'verbose_name_plural': 'After sale files'},
        ),
        migrations.AlterModelOptions(
            name='sav_file_status',
            options={'verbose_name': 'after sale file status', 'verbose_name_plural': 'after sale file status'},
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(default='', max_length=100, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='refered_SAV_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.SAV_file', verbose_name='After sale file'),
        ),
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.TextField(verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='refered_SAV_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.SAV_file', verbose_name='After sale file'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='furnisher',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='furnisher',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='Commentary'),
        ),
        migrations.AlterField(
            model_name='furnisher',
            name='complements',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Complements'),
        ),
        migrations.AlterField(
            model_name='furnisher',
            name='mark',
            field=models.CharField(default='', max_length=200, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='furnisher',
            name='phone',
            field=models.CharField(default='', max_length=200, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='furnisher',
            name='street',
            field=models.CharField(default='', max_length=300, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='furnisher',
            name='zipcode',
            field=models.CharField(default='', max_length=30, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='complements',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Complements'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='guarantee_time',
            field=models.CharField(default='', max_length=20, verbose_name='Waranty_time'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='mark',
            field=models.CharField(default='', max_length=200, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='procedure',
            field=models.TextField(verbose_name='Procedure'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='city_client',
            field=models.CharField(default='', max_length=100, verbose_name='Customer city'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='client_bill',
            field=models.FileField(blank=True, upload_to=b'', verbose_name='Client bill'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='complements_client',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Customer address complements'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='email_client',
            field=models.CharField(default='', max_length=100, verbose_name='Customer email'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='furnisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='visualImpactSAV.Furnisher', verbose_name='Furnisher'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='guarantee',
            field=models.CharField(default='Sous garantie', max_length=100, verbose_name='Waranty'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='mark_product',
            field=models.CharField(default='', max_length=200, verbose_name='Product brand'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='name_client',
            field=models.CharField(default='', max_length=300, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='name_product',
            field=models.CharField(default='', max_length=200, verbose_name='Product model'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='out_of_order_reason',
            field=models.TextField(verbose_name='Out of order reason'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='phone_client',
            field=models.CharField(default='', max_length=30, verbose_name='Customer phone'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='registred_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='rma_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Product RMA number'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='sav_file_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.SAV_file_status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='serial_number_product',
            field=models.CharField(default='', max_length=200, verbose_name='Product serial number'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='society_client',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Society'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='street_client',
            field=models.CharField(default='', max_length=300, verbose_name='Customer street'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='zipcode_client',
            field=models.CharField(default='', max_length=30, verbose_name='Customer zipcode'),
        ),
    ]
