# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0020_auto_20180924_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='refered_SAV_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='visualImpactSAV.SAV_file', verbose_name='After sale file'),
        ),
    ]
