# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0025_auto_20180926_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='refered_SAV_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='visualImpactSAV.SAV_file', verbose_name='After sale file'),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='guarantee',
            field=models.CharField(default='Included waranty', max_length=100, verbose_name='Waranty'),
        ),
    ]
