# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-09 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0027_auto_20181007_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_file',
            name='status',
            field=models.CharField(choices=[('IW', 'Sous garantie'), ('EW', 'Hors garantie')], default='O', max_length=20, verbose_name='Status'),
        ),
    ]
