# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0033_auto_20181011_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sav_file',
            name='sav_file_status',
        ),
        migrations.DeleteModel(
            name='SAV_file_status',
        ),
    ]
