# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=300)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=400)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('action', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SAV_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_of_order_reason', models.TextField()),
                ('file_import_export_note', models.FileField(upload_to=b'')),
                ('file_import_export_reparation_client_side', models.FileField(upload_to=b'')),
                ('file_import_export_reparation_furnisher_side', models.FileField(upload_to=b'')),
                ('reparation_validated', models.BooleanField()),
                ('traking_number', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SAV_file_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sav_file',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.SAV_file_status'),
        ),
        migrations.AddField(
            model_name='event',
            name='refered_SAV_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.SAV_file'),
        ),
    ]
