# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sav_file',
            name='reparation_status',
        ),
        migrations.DeleteModel(
            name='Reparation_status',
        ),
    ]
