# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.Address'),
        ),
    ]
