# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualImpactSAV', '0002_auto_20171109_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_file',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
