# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0002_auto_20170721_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sav_file',
            old_name='traking_number',
            new_name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='sav_file',
            name='id',
        ),
        migrations.AddField(
            model_name='sav_file',
            name='file_reference',
            field=models.CharField(default='0', max_length=50, primary_key=True, serialize=False),
        ),
    ]
