# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 23:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0003_sav_file_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sav_file',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
