# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0004_auto_20170724_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('action', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SAV_file',
            fields=[
                ('file_reference', models.CharField(default='0', max_length=50, primary_key=True, serialize=False)),
                ('out_of_order_reason', models.TextField()),
                ('file_import_export_note', models.FileField(upload_to=b'')),
                ('file_import_export_reparation_client_side', models.FileField(upload_to=b'')),
                ('file_import_export_reparation_furnisher_side', models.FileField(upload_to=b'')),
                ('reparation_validated', models.BooleanField()),
                ('tracking_number', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.Product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.SAV_file_status')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='refered_SAV_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.SAV_file'),
        ),
    ]
