# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0005_auto_20170724_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sav_file',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sav_file',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sav_file',
            name='status',
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='file_import_export_note',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='file_import_export_reparation_client_side',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='file_import_export_reparation_furnisher_side',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='sav_file',
            name='reparation_validated',
            field=models.BooleanField(default=False),
        ),
    ]
