# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0006_auto_20170724_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_file',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.Client'),
        ),
        migrations.AddField(
            model_name='sav_file',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.Product'),
        ),
        migrations.AddField(
            model_name='sav_file',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.SAV_file_status'),
        ),
    ]
