# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0007_auto_20170725_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sav_file',
            old_name='product',
            new_name='product_referenced',
        ),
    ]
