# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0008_auto_20170725_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparation_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sav_file',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sav_file',
            name='product_referenced',
        ),
        migrations.RemoveField(
            model_name='sav_file',
            name='reparation_validated',
        ),
        migrations.RemoveField(
            model_name='sav_file',
            name='status',
        ),
        migrations.AddField(
            model_name='sav_file',
            name='city_client',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sav_file',
            name='email_client',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sav_file',
            name='mark_product',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sav_file',
            name='name_client',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sav_file',
            name='name_product',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sav_file',
            name='phone_client',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sav_file',
            name='serial_number_product',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sav_file',
            name='street_client',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sav_file',
            name='zipcode_client',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
