# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0009_auto_20170805_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_file',
            name='reparation_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.Reparation_status'),
        ),
        migrations.AddField(
            model_name='sav_file',
            name='sav_file_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.SAV_file_status'),
        ),
    ]
