# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0010_remove_sav_file_reference_sav_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(default='', max_length=200)),
                ('complements', models.CharField(default='', max_length=200)),
                ('guarantee_time', models.CharField(default='', max_length=20)),
                ('procedure', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='sav_file',
            name='complements_client',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
