# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0010_auto_20170805_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_file',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
