# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0011_sav_file_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sav_file',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 16, 26, 5, 64108)),
        ),
    ]
