# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0011_auto_20180303_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='procedure',
            field=models.TextField(),
        ),
    ]
