# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0012_auto_20180313_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('street', models.CharField(default='', max_length=300)),
                ('complements', models.CharField(blank=True, default='', max_length=300)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('city', models.CharField(default='', max_length=10)),
                ('commentary', models.TextField()),
            ],
        ),
    ]
