# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0012_auto_20170805_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sav_file',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
