# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0013_auto_20170805_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sav_file',
            name='email_client',
            field=models.CharField(default='', max_length=100),
        ),
    ]
