# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0014_auto_20170805_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_file_status',
            name='class_css',
            field=models.CharField(default='', max_length=50),
        ),
    ]
