# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0016_auto_20170805_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sav_file',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
