# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0016_auto_20180524_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sav_file',
            name='guarantee',
            field=models.CharField(default='Sous garantie', max_length=100),
        ),
    ]
