# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0017_auto_20170812_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pdf_client_invoice_file',
            fields=[
                ('filename', models.CharField(default='invoice_client.pdf', max_length=30)),
                ('refered_sav_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='refered_sav_file', serialize=False, to='visualImpactSAV.SAV_file')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='designation',
            name='refered_pdf_client_invoice_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualImpactSAV.Pdf_client_invoice_file'),
        ),
    ]
