# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0018_auto_20170825_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sav_file',
            name='file_reference',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False),
        ),
    ]
