# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0019_auto_20170826_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sav_file',
            old_name='file_import_export_note',
            new_name='client_bill',
        ),
        migrations.RenameField(
            model_name='sav_file',
            old_name='file_import_export_reparation_client_side',
            new_name='furnisher_invoice',
        ),
        migrations.RemoveField(
            model_name='sav_file',
            name='file_import_export_reparation_furnisher_side',
        ),
        migrations.AddField(
            model_name='sav_file',
            name='society_client',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
