# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0021_auto_20180925_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=200, verbose_name='Brand')),
                ('complements', models.CharField(blank=True, default='', max_length=200, verbose_name='Complements')),
                ('waranty_time', models.CharField(default='', max_length=20, verbose_name='Waranty time')),
                ('procedure', models.TextField(verbose_name='Procedure')),
            ],
            options={
                'ordering': ['brand'],
                'verbose_name': 'waranty',
                'verbose_name_plural': 'waranties',
            },
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='guarantee_time',
            field=models.CharField(default='', max_length=20, verbose_name='Waranty time'),
        ),
    ]
