# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0022_auto_20180925_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guarantee',
        ),
        migrations.AlterModelOptions(
            name='furnisher',
            options={'ordering': ['brand'], 'verbose_name': 'furnisher', 'verbose_name_plural': 'furnishers'},
        ),
        migrations.AddField(
            model_name='furnisher',
            name='brand',
            field=models.CharField(default='', max_length=200, verbose_name='Brand'),
        ),
    ]
