# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0022_auto_20170828_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sav_file',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
