# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0024_remove_furnisher_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name': 'designation', 'verbose_name_plural': 'designations'},
        ),
    ]
