# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0024_auto_20170829_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='refered_pdf_client_invoice_file',
            new_name='refered_SAV_file',
        ),
    ]
