# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0025_auto_20170829_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf_generation_file',
        ),
    ]
