# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0029_auto_20181010_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sav_file',
            old_name='client_bill',
            new_name='bill_customer',
        ),
        migrations.RenameField(
            model_name='sav_file',
            old_name='city_client',
            new_name='city_customer',
        ),
        migrations.RenameField(
            model_name='sav_file',
            old_name='complements_client',
            new_name='complements_customer',
        ),
        migrations.RenameField(
            model_name='sav_file',
            old_name='email_client',
            new_name='email_customer',
        ),
        migrations.RenameField(
            model_name='sav_file',
            old_name='name_client',
            new_name='name_customer',
        ),
        migrations.RenameField(
            model_name='sav_file',
            old_name='phone_client',
            new_name='phone_customer',
        ),
        migrations.RenameField(
            model_name='sav_file',
            old_name='society_client',
            new_name='society_customer',
        ),
        migrations.RenameField(
            model_name='sav_file',
            old_name='street_client',
            new_name='street_customer',
        ),
        migrations.RenameField(
            model_name='sav_file',
            old_name='zipcode_client',
            new_name='zipcode_customer',
        ),
    ]
