# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0032_auto_20181011_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sav_file',
            old_name='guarantee',
            new_name='waranty',
        ),
    ]
