# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0035_auto_20181026_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='sav_file',
            name='given_accessory',
            field=models.TextField(blank=True, verbose_name='Given accessory'),
        ),
    ]
