# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-27 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualImpactSAV', '0037_auto_20181117_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAndPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(default='', max_length=300, verbose_name='Customer name')),
                ('email_customer', models.CharField(default='', max_length=100, verbose_name='Customer email')),
                ('phone_customer', models.CharField(blank=True, default='', max_length=30, verbose_name='Customer phone')),
            ],
        ),
        migrations.CreateModel(
            name='SessionMailAndPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='sav_file',
            options={'ordering': ['-creation_date'], 'verbose_name': 'After sale file', 'verbose_name_plural': 'After sale files'},
        ),
        migrations.AddField(
            model_name='mailandphone',
            name='in_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mailAndPhones', to='visualImpactSAV.SessionMailAndPhone'),
        ),
    ]
